FROM node:alpine
WORKDIR /app

COPY node_modules/@prisma/client ./node_modules/@prisma/client
COPY prisma ./prisma
COPY prisma.config.ts ./prisma.config.ts

RUN npm install prisma --no-save

CMD ["npx", "prisma", "migrate", "deploy"]
